version: '3.8'

services:
  zamazon-service:
    build: .
    container_name: zamazon_service
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: Anmol@8907
      DB_NAME: Zamazondb
      DB_TEST_NAME: database_test
      DB_PROD_NAME: database_production
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - zamazon-postgres

  zamazon-postgres:
    image: postgres:15
    container_name: zamazon_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Anmol@8907
      POSTGRES_DB: Zamazondb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
